---
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: cloudbolt

  tasks:

  - name: install ssh key
    authorized_key: user=cloudbolt 
                    key="{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}" 
                    state=present
